### ISSUE TITLE
SDK not working with Expo React Native

### ISSUE THREAD

**Issue by chongdog83** [Baqend/js-sdk#21]
On Android only, when I create a new project in Expo and then install baqend like this:

`npm install baqend --save`

Then use it in the project by importing it:
`import { db } from 'baqend';`

The android emulator (and my phone) starts throwing errors.

At first I thought maybe it was one of the other libraries I'm using, but in order to track this down, I started a brand new project in Expo, then started added packages one at a time.

Here's the package.json:
```
{
  "name": "my-new-project",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "baqend": "2.8.5",
    "expo": "29.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
    "react-navigation": "^2.9.3"
  },
  "devDependencies": {
    "jest-expo": "29.0.0"
  }
}
```

Now you will notice that in the above I'm using 2.8.5. I tested several releases while troubleshooting and found that 2.8.5 and lower produces one error.  The more recent releases produce a different error.

2.8.5 version procudes this errror (on the packager):
`/Documents/my-new-project/node_modules/baqend/dist/baqend.js: Unknown plugin "transform-proto-to-assign" specified in "/Users/chris/Documents/my-new-project/node_modules/baqend/.babelrc" at 0, attempted to resolve relative to "/Users/chris/Documents/my-new-project/node_modules/baqend"`

And this error on the Android emulator (Android 7):
```
The development server returned response error code: 500

URL: http://localhost:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fchris%2FDocuments%2Fmy-new-project%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles

Body:
{"type":"TransformError","lineNumber":0,"errors":[{"description":"/Users/chris/Documents/my-new-project/node_modules/baqend/dist/baqend.js: Unknown plugin \"transform-proto-to-assign\" specified in \"/Users/chris/Documents/my-new-project/node_modules/baqend/.babelrc\" at 0, attempted to resolve relative to \"/Users/chris/Documents/my-new-project/node_modules/baqend\"","lineNumber":0}],"name":"SyntaxError","message":"/Users/chris/Documents/my-new-project/node_modules/baqend/dist/baqend.js: Unknown plugin \"transform-proto-to-assign\" specified in \"/Users/chris/Documents/my-new-project/node_modules/baqend/.babelrc\" at 0, attempted to resolve relative to \"/Users/chris/Documents/my-new-project/node_modules/baqend\"","stack":"ReferenceError: Unknown plugin \"transform-proto-to-assign\" specified in \"/Users/chris/Documents/my-new-project/node_modules/baqend/.babelrc\" at 0, attempted to resolve relative to \"/Users/chris/Documents/my-new-project/node_modules/baqend\"\n    at /Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17\n    at Array.map (native)\n    at Function.normalisePlugins (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)\n    at OptionManager.mergeOptions (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)\n    at OptionManager.init (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)\n    at File.initOptions (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/index.js:212:65)\n    at new File (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/file/index.js:135:24)\n    at Pipeline.transform (/Users/chris/Documents/my-new-project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)\n    at Object.transform (/Users/chris/Documents/my-new-project/node_modules/metro/src/transformer.js:135:5)"}
processBundleResult
    BundleDownloader.java:268
access$200
    BundleDownloader.java:35
onChunkComplete
    BundleDownloader.java:195
emitChunk
    MultipartStreamReader.java:76
readAllParts
    MultipartStreamReader.java:154
processMultipartResponse
    BundleDownloader.java:179
access$100
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:148
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764
```

Now, when I use any version greater than 2.8.5 I get a different error.  

Here is the error using 2.12.3 (in this case its the error is only on the phone, no errors in the packager):

 ```
is not iterable!
exports
    _for-of.js:14:51
<unknown>
    _collection.js:61:41
Set
    es6.set.js:8:37
<unknown>
    Asset.js:21:30
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:141:45
_require
    require.js:132:20
Asset
    index.js:3:11
Asset
    Expo.js:62:33
_callee$
    App.js:32:6
tryCatch
    runtime.js:62:44
invoke
    runtime.js:296:30
<unknown>
    runtime.js:114:28
tryCatch
    runtime.js:62:44
invoke
    runtime.js:152:28
<unknown>
    runtime.js:195:17
tryCallTwo
    core.js:45:7
doResolve
    core.js:200:23
Promise
    core.js:66:12
callInvokeWithMethodAndArg
    runtime.js:194:27
enqueue
    runtime.js:217:12
<unknown>
    runtime.js:114:28
async
    runtime.js:241:8
_callee
    App.js:30:24
_callee$
    AppLoading.js:48:12
tryCatch
    runtime.js:62:44
invoke
    runtime.js:296:30
<unknown>
    runtime.js:114:28
tryCatch
    runtime.js:62:44
invoke
    runtime.js:152:28
<unknown>
    runtime.js:195:17
tryCallTwo
    core.js:45:7
doResolve
    core.js:200:23
Promise
    core.js:66:12
callInvokeWithMethodAndArg
    runtime.js:194:27
enqueue
    runtime.js:217:12
<unknown>
    runtime.js:114:28
async
    runtime.js:241:8
_callee
    AppLoading.js:42:35
componentDidMount
    AppLoading.js:31:6
proxiedComponentDidMount
    createPrototypeProxy.js:61:45
commitLifeCycles
    ReactNativeRenderer-dev.js:10627:12
commitAllLifeCycles
    ReactNativeRenderer-dev.js:12512:10
invokeGuardedCallback
    ReactNativeRenderer-dev.js:39:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:221:34
commitRoot
    ReactNativeRenderer-dev.js:12677:10
completeRoot
    ReactNativeRenderer-dev.js:13685:46
performWorkOnRoot
    ReactNativeRenderer-dev.js:13635:23
performWork
    ReactNativeRenderer-dev.js:13545:26
performSyncWork
    ReactNativeRenderer-dev.js:13506:16
requestWork
    ReactNativeRenderer-dev.js:13392:6
scheduleWorkImpl
    ReactNativeRenderer-dev.js:13259:24
scheduleWork
    ReactNativeRenderer-dev.js:13207:28
scheduleRootUpdate
    ReactNativeRenderer-dev.js:13930:17
_updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:13966:6
updateContainer
    ReactNativeRenderer-dev.js:13991:8
render
    ReactNativeRenderer-dev.js:14726:35
renderApplication
    renderApplication.js:49:21
run
    AppRegistry.js:102:10
runApplication
    AppRegistry.js:194:26
__callFunction
    MessageQueue.js:351:47
<unknown>
    MessageQueue.js:116:26
__guardSafe
    MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17
```

What would be awesome is for the latest version of the sdk to work on the latest version of expo.

**To replicate:**

In expo, create "my new project" use Tabbed Navigation preset.

Open it up on your android phone over wifi or use the android emulator.  It works fine.

Now go to the newly created my-new-project folder and run `npm install baqend --save `  this installs 2.12.3.

Then open up /screens/HomeScreen.js  and add import { db } from 'baqend' to the top

Save it. Restart packager. Re-open project on your phone or emulator. Error happens as app starts.

Please let me know if I can help fix this.  I'm not a really a developer but I'll do what I can.

**Comment by mndfcked** [comment]
This problem can be solved by installing the missing plugins with
`npm install babel-plugin-transform-proto-to-assign -save` and `npm install babel-preset-es2015 -save`

**Comment by chongdog83** [comment]
I tried that and it kind of worked but created errors elsewhere.

Ultimately upgrading to expo version 30 made everything work as expected.
